### ISSUE TITLE
Does not work with VS Code 1.9.0

### ISSUE THREAD

**Issue by sqnkov** [richie5um/vscode-snake-trail#2]
@richie5um, this is a really crazy feature that I was looking for, but it seems to be beyond buggy in 1.9.0

Are you willing to consider fixing this? 

![snake](https://cloud.githubusercontent.com/assets/9406520/22697923/9fefcca4-ed5b-11e6-862e-d1978ff8b8e7.gif)

**Comment by richie5um** [comment]
I'm on 1.9.0 too (macOS 10.12.3) and it is fine - I'm working on Typescript/Javascript/JSON files.

Does it fail in every filetype for you?
It could be another extension you have installed - the way it works is a bit of a bun-fight.

**Comment by sqnkov** [comment]
Well, I guess that could be the issue, the bad thing is I can't really figure out what is causing it. Thanks for your fast response anyway!

**Comment by richie5um** [comment]
Snake Trail needs all the users it can get :)

If you create a new file (and ensure the type is 'Plain Text') does Snake Trail work then?

![image](https://cloud.githubusercontent.com/assets/907033/22699854/9b9df654-ed50-11e6-8098-a80eb6c6b455.png)

**Comment by richie5um** [comment]
What extension do you use for the CSS color (to show the background in the css color)?

**Comment by sqnkov** [comment]
Not sure exactly what you mean @richie5um , but I use the integrated stuff from VS Code and I have installed the Material Theme (Dark). No other visual modifiers (except linting underline scribbles - [style-lint] and some Guides + Indenticator.

```
auto-close-tag - Version :0.3.9
auto-rename-tag - Version :0.0.11
beautify - Version :0.7.3
Bookmarks - Version :0.10.2
bracket-pair-colorizer - Version :0.2.1
code-settings-sync - Version :2.4.3
color-highlight - Version :1.3.1
gitignore - Version :0.5.0
guides - Version :0.6.1
html-snippets - Version :0.0.18
HTMLHint - Version :0.3.3
htmltagwrap - Version :0.0.3
indenticator - Version :0.2.1
lorem-ipsum - Version :1.0.0
path-intellisense - Version :1.2.0
php-intellisense - Version :1.1.1
stylelint - Version :0.22.0
theme-material-theme - Version :1.0.1
vscode-autoprefixer - Version :2.0.0
vscode-color - Version :0.2.3
vscode-eslint - Version :1.2.4
vscode-great-icons - Version :1.1.44
vscode-html-css - Version :0.0.33
vscode-scss - Version :0.6.1
vscode-svgviewer - Version :1.3.1
vscode-todo-highlight - Version :0.3.3
```

**Comment by richie5um** [comment]
Unable to reproduce. Hope it now works for you.
