### ISSUE TITLE
Considering an update

### ISSUE THREAD

**Issue by rbeesley** [richie5um/vscode-snake-trail#3]
In my own repro I've started making changes, which in theory could be brought back in as a PR. However, I'm taking it in a direction which doesn't really fit the description of what Snake Trail is today. You said in your README that you would rather have PR changes than a fork, but if I finish the ideas I have in mind, I think that a different name would be appropriate for the extension and it would no longer be Snake Trails. I'd attach the appropriate citations to reference back to this project, but as it hasn't been updated in 4 years, would you be terribly upset if I used parts of this project to publish something new instead of trying to evolve this into something else?

**Comment by richie5um** [comment]
Hey. Thanks for getting in contact - appreciate you asking first. 

Can you give a basic outline of what you are thinking of doing?

**Comment by rbeesley** [comment]
Sure, so my plan is to implement more of a CRT phosphor fade. To help facilitate this, I've replaced the linear opacity changing with half of a smoothstep, so that there is a faster falloff and a longer lasting lower intensity after glow. I am intending to highlight added text with one color and (maybe?) show deleted text in a different color. I've also gone and updated the dependencies to make it work with current typings and vscode. Because I'm interested in making this more like a CRT, the idea of snakes makes less sense. I could probably contribute some of the changes I had to make to bring the project up to speed with current tools, and I made it so that you don't have to reload to import setting changes, but I don't think it makes sense replacing the opacity interpolation algorithm for just my purpose and it seems like a departure. Conceivably you could add a way to introduce presets as a theme, but the settings is already really messy trying to support these different methods, especially since my current implementation of smoothstep to produce the result I'm trying to achieve has 6 parameters to control it alone and independent from what already existed. Your project got me started, but other than using it to learn how to add decorations and animate them, it's a pretty significant change at this point. I could contribute some of the changes I've made, but I think it might make sense to make it a different extension rather than a modification or update.

**Comment by richie5um** [comment]
Your idea sounds cool. I agree with you, definitely feels like a different extension. Good luck, and let me know when you’ve released it :).

**Comment by rbeesley** [comment]
I made my first check in of the code in a new repository, [vscode-edit-phosphor](https://github.com/rbeesley/vscode-edit-phosphor), retaining the git history. Still lots to change, but this can at least be a starting point if there are parts you want me to back port to vscode-snake-trail.
